CompanyNotes/Controllers/CasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CompanyNotes.Models;

namespace CompanyNotes.Controllers
{
    public class CasesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cases
        public ActionResult Index()
        {
            var cases = db.Cases.Include(x => x.Client);

            return View(cases.ToList());
        }

        // GET: Cases/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Case @case = db.Cases.Find(id);
            if (@case == null)
            {
                return HttpNotFound();
            }
            return View(@case);
        }

        // GET: Cases/Create
        public ActionResult Create()
        {
            ViewBag.ClientId = new SelectList(db.Clients, "ClientId", "ClientName");
            
            var managers = db.Employees.Where(e => e.WorkTitle.Name == "Site Manager");
            ViewBag.Managers = new SelectList(managers, "FullName", "FullName");

            return View();
        }

        // POST: Cases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CaseId,Address,StartDate,EndDate,IsActive,Manager,ClientId")] Case @case)
        {
            if (ModelState.IsValid)
            {
                int lastCaseNumberInDb = db.Cases.OrderByDescending(c => c.CaseNumber).Select(cn => cn.CaseNumber).FirstOrDefault();

                @case.CaseNumber = @case.setCaseNumber(lastCaseNumberInDb);
                db.Cases.Add(@case);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClientId = new SelectList(db.Clients, "ClientId", "ClientName", @case.ClientId);
            
            return View(@case);
        }

        // GET: Cases/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Case @case = db.Cases.Find(id);
            if (@case == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClientId = new SelectList(db.Clients, "ClientId", "ClientName", @case.ClientId);

            var managers = db.Employees.Where(e => e.WorkTitle.Name == "Site Manager");
            ViewBag.Managers = new SelectList(managers, "FullName", "FullName");

            return View(@case);
        }

        // POST: Cases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CaseId,CaseNumber,Address,StartDate,EndDate,IsActive,Manager,ClientId")] Case @case)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@case).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClientId = new SelectList(db.Clients, "ClientId", "ClientName", @case.ClientId);
            return View(@case);
        }

        // GET: Cases/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Case @case = db.Cases.Find(id);
            if (@case == null)
            {
                return HttpNotFound();
            }
            return View(@case);
        }

        // POST: Cases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Case @case = db.Cases.Find(id);
            db.Cases.Remove(@case);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CompanyNotes/Controllers/ResidentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CompanyNotes.Models;
using CompanyNotes.ViewModels;

namespace CompanyNotes.Controllers
{
    public class ResidentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //// GET: Residents
        //public ActionResult Index()
        //{
        //    var residents = db.Residents.Include(r => r.Case);
        //    return View(residents.ToList());
        //}

        // GET: Residents
        public ActionResult ResidentsForCase(int caseId, int caseNumber)
        {
            var residentsForCurrentCase = db.Residents.Where(r => r.CaseId == caseId);

            if (!residentsForCurrentCase.Any())
            {
                ViewBag.CaseId = caseId;
                ViewBag.CaseNumber = caseNumber;
                return View("NoResidentsFound");
            }

            ViewBag.CaseId = caseId;
            ViewBag.CaseNumber = caseNumber;
            return View(residentsForCurrentCase);
        }


        // GET: Residents/Create
        public ActionResult Create(int caseId, int caseNumber)
        {
            CreateResidentViewModel viewModel = new CreateResidentViewModel
            {
                CaseId = caseId,
                CaseNumber = caseNumber
            };

            return View(viewModel);
        }

        // POST: Residents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateResidentViewModel model)
        {
            if (ModelState.IsValid)
            {
                Resident resident = new Resident
                {
                    ResidentId = 0,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Address = model.Address,
                    Email = model.Email,
                    Phone = model.Phone,
                    CaseId = model.CaseId
                };
                db.Residents.Add(resident);
                db.SaveChanges();
                return RedirectToAction("ResidentsForCase", new { caseId = model.CaseId, caseNumber = model.CaseNumber });
            }

            return RedirectToAction("ResidentsForCase", new { caseId = model.CaseId, caseNumber = model.CaseNumber });
        }

        // GET: Residents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resident resident = db.Residents.Find(id);
            if (resident == null)
            {
                return HttpNotFound();
            }
            ViewBag.CaseId = new SelectList(db.Cases, "CaseId", "CaseNumber", resident.CaseId);
            return View(resident);
        }

        // POST: Residents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ResidentId,FirstName,LastName,Address,Email,Phone,CaseId")] Resident resident)
        {
            if (ModelState.IsValid)
            {
                db.Entry(resident).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ResidentsForCase", new { caseId = resident.CaseId });
            }
            //ViewBag.CaseId = new SelectList(db.Cases, "CaseId", "Address", resident.CaseId);
            //return View(resident);
            return RedirectToAction("ResidentsForCase", new { caseId = resident.CaseId });
        }

        // GET: Residents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resident resident = db.Residents.Find(id);
            if (resident == null)
            {
                return HttpNotFound();
            }
            return View(resident);
        }

        // POST: Residents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Resident resident = db.Residents.Find(id);
            db.Residents.Remove(resident);
            db.SaveChanges();
            return RedirectToAction("ResidentsForCase", new { caseId = resident.CaseId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CompanyNotes/Controllers/WorkNotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CompanyNotes.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace CompanyNotes.Controllers
{
    public class WorkNotesController : Controller
    {
        protected ApplicationDbContext db { get; set; }
        protected UserManager<ApplicationUser> UserManager { get; set; }  // User manager - attached to application DB context

        public WorkNotesController()
        {
            this.db = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.db));
        }

        // GET: WorkNotes for an employee
        public ActionResult Index()
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            ViewBag.Employee = user.Employee;

            //var workNotes = db.WorkNotes.Include(w => w.Case).Include(w => w.Employee);
            var workNotes = db.WorkNotes.Include(w => w.Case).Include(w => w.Employee).Where(e => e.EmployeeId == user.Employee.EmployeeId);

            return View(workNotes.ToList());
        }

        // GET: WorkNotes for a case
        public ActionResult NotesForCase(int caseId)
        {
            var workNotes = db.WorkNotes.Where(w => w.CaseId == caseId).Include(w => w.Employee);
            ViewBag.CaseNumber = db.Cases.Where(c => c.CaseId == caseId).Select(c => c.CaseNumber).FirstOrDefault();

            return View(workNotes.ToList());
        }

        // GET: WorkNotes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkNote workNote = db.WorkNotes.Find(id);
            if (workNote == null)
            {
                return HttpNotFound();
            }
            return View(workNote);
        }

        // GET: WorkNotes/Create
        public ActionResult Create()
        {
            ViewBag.CaseId = new SelectList(db.Cases, "CaseId", "Address");

            var user = UserManager.FindById(User.Identity.GetUserId());

            WorkNote note = new WorkNote
            {
                WorkNoteId = 0,
                Date = DateTime.Now,
                Caption = null,
                Text = null,
                CaseId = -1,
                EmployeeId = user.Employee.EmployeeId,
                Employee = user.Employee
            };                
            
            return View(note);
        }

        // POST: WorkNotes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "WorkNoteId,Date,Caption,Text,CaseId,EmployeeId")] WorkNote workNote)
        {
            if (ModelState.IsValid)
            {
                db.WorkNotes.Add(workNote);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CaseId = new SelectList(db.Cases, "CaseId", "Address", workNote.CaseId);
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FirstName", workNote.EmployeeId);
            return View(workNote);
        }

        // GET: WorkNotes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkNote workNote = db.WorkNotes.Find(id);
            if (workNote == null)
            {
                return HttpNotFound();
            }
            ViewBag.CaseId = new SelectList(db.Cases, "CaseId", "Address", workNote.CaseId);
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FirstName", workNote.EmployeeId);
            return View(workNote);
        }

        // POST: WorkNotes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WorkNoteId,Date,Caption,Text,CaseId,EmployeeId")] WorkNote workNote)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workNote).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("NotesForCase", new { caseId = workNote.CaseId} );
            }
            ViewBag.CaseId = new SelectList(db.Cases, "CaseId", "Address", workNote.CaseId);
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "FirstName", workNote.EmployeeId);
            return View(workNote);
        }

        // GET: WorkNotes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkNote workNote = db.WorkNotes.Find(id);
            if (workNote == null)
            {
                return HttpNotFound();
            }
            return View(workNote);
        }

        // POST: WorkNotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkNote workNote = db.WorkNotes.Find(id);
            db.WorkNotes.Remove(workNote);
            db.SaveChanges();
            return RedirectToAction("NotesForCase", new { caseId = workNote.CaseId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CompanyNotes/Views/Cases/Create.cshtml
@model CompanyNotes.Models.Case

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Case</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manager, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Manager", (SelectList) ViewBag.Managers, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Manager, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, "ClientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CompanyNotes/Views/Cases/Delete.cshtml
@model CompanyNotes.Models.Case

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Case No. @Model.CaseNumber</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Case</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.ClientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.ClientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manager)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manager)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CompanyNotes/Views/Cases/Details.cshtml
@model CompanyNotes.Models.Case

@{
    ViewBag.Title = "Details";
}

<h2>Details Case No. @Model.CaseNumber</h2>

<div>
    <h4>Case</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Client.ClientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.ClientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manager)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manager)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CaseId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CompanyNotes/Views/Cases/Edit.cshtml
@model CompanyNotes.Models.Case

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Case No. @Model.CaseNumber</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Case</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CaseId)
        @Html.HiddenFor(model => model.CaseNumber)

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, null, new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manager, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Manager, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("Manager", (SelectList)ViewBag.Managers, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Manager, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, "ClientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CompanyNotes/Views/Cases/Index.cshtml
@model IEnumerable<CompanyNotes.Models.Case>

@{
    ViewBag.Title = "Index";
}

<h2>Index All Cases</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CaseNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorkNotes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Residents)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CaseNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.ActionLink("Show Notes", "NotesForCase", "WorkNotes", new { caseId = item.CaseId }, null)
        </td>

            @if (item.IsActive)
            {
                <td>
                    <div style="border: 1px solid black; background-color: #00FF00">
                        <span>&nbsp; Case Active</span>
                    </div>
                </td>
            }
            else if (!item.IsActive)
            {
                <td>
                    <div style="border: 1px solid black; background-color: #f80d0d">
                        <span>&nbsp; Case Closed</span>
                    </div>
                </td>
            }

        <td>
            @Html.ActionLink("List of Residents", "ResidentsForCase", "Residents",
                                                    new { caseId = item.CaseId, caseNumber = item.CaseNumber }, null)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.CaseId }) |
            @Html.ActionLink("Details", "Details", new { id = item.CaseId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.CaseId })
        </td>
    </tr>
}

</table>